'use client'

import { useState } from 'react'
import { X, Bug, Copy, Check, Clock } from 'lucide-react'
import clsx from 'clsx'

interface BugReportDialogProps {
    onClose: () => void
}

const BUG_TYPES = [
    { value: 'ui', label: 'UI Issue', emoji: '🎨' },
    { value: 'api', label: 'API Error', emoji: '🔌' },
    { value: 'performance', label: 'Performance', emoji: '🐌' },
    { value: 'unexpected', label: 'Unexpected Behavior', emoji: '🤔' },
    { value: 'crash', label: 'Crash/Freeze', emoji: '💥' },
    { value: 'other', label: 'Other', emoji: '📝' }
]

export function BugReportDialog({ onClose }: BugReportDialogProps) {
    const [bugType, setBugType] = useState('unexpected')
    const [description, setDescription] = useState('')
    const [steps, setSteps] = useState('')
    const [copied, setCopied] = useState(false)

    // Generate timestamp for log correlation
    const timestamp = new Date().toISOString()
    const displayTime = new Date().toLocaleString()

    const generateReport = () => {
        const typeInfo = BUG_TYPES.find(t => t.value === bugType)
        return `## Bug Report

**Timestamp:** ${timestamp}
**Type:** ${typeInfo?.emoji} ${typeInfo?.label}

### Description
${description || '(No description provided)'}

${steps ? `### Steps to Reproduce\n${steps}` : ''}

---
*Generated by Chorum Bug Reporter*`
    }

    const handleCopy = async () => {
        const report = generateReport()
        await navigator.clipboard.writeText(report)
        setCopied(true)
        setTimeout(() => setCopied(false), 2000)
    }

    return (
        <div className="fixed inset-0 bg-black/60 backdrop-blur-sm flex items-center justify-center z-50 p-4">
            <div className="bg-gray-900 border border-gray-700 rounded-xl max-w-lg w-full shadow-2xl">
                {/* Header */}
                <div className="flex items-center justify-between p-4 border-b border-gray-800">
                    <div className="flex items-center gap-2">
                        <Bug className="w-5 h-5 text-red-400" />
                        <h2 className="text-lg font-semibold text-gray-100">Report a Bug</h2>
                    </div>
                    <button
                        onClick={onClose}
                        className="p-1 hover:bg-gray-800 rounded-lg text-gray-500 hover:text-gray-300 transition-colors"
                    >
                        <X className="w-5 h-5" />
                    </button>
                </div>

                {/* Content */}
                <div className="p-4 space-y-4">
                    {/* Timestamp for log correlation */}
                    <div className="flex items-center gap-2 px-3 py-2 bg-gray-800/50 rounded-lg border border-gray-700">
                        <Clock className="w-4 h-4 text-gray-500" />
                        <span className="text-xs text-gray-400">Timestamp:</span>
                        <code className="text-xs text-blue-400 font-mono">{displayTime}</code>
                    </div>

                    {/* Bug Type */}
                    <div>
                        <label className="block text-sm font-medium text-gray-300 mb-2">
                            Bug Type
                        </label>
                        <div className="grid grid-cols-3 gap-2">
                            {BUG_TYPES.map(type => (
                                <button
                                    key={type.value}
                                    onClick={() => setBugType(type.value)}
                                    className={clsx(
                                        'px-3 py-2 rounded-lg text-sm transition-all border',
                                        bugType === type.value
                                            ? 'bg-blue-600/20 border-blue-500/50 text-blue-300'
                                            : 'bg-gray-800/50 border-gray-700 text-gray-400 hover:bg-gray-800 hover:text-gray-300'
                                    )}
                                >
                                    <span className="mr-1">{type.emoji}</span>
                                    <span className="text-xs">{type.label}</span>
                                </button>
                            ))}
                        </div>
                    </div>

                    {/* Description */}
                    <div>
                        <label className="block text-sm font-medium text-gray-300 mb-2">
                            What happened? <span className="text-red-400">*</span>
                        </label>
                        <textarea
                            value={description}
                            onChange={(e) => setDescription(e.target.value)}
                            placeholder="Describe the bug..."
                            className="w-full bg-gray-800 border border-gray-700 rounded-lg px-3 py-2 text-sm text-gray-200 placeholder-gray-500 focus:outline-none focus:ring-1 focus:ring-blue-500 focus:border-blue-500 resize-none"
                            rows={3}
                        />
                    </div>

                    {/* Steps to Reproduce */}
                    <div>
                        <label className="block text-sm font-medium text-gray-300 mb-2">
                            Steps to Reproduce <span className="text-gray-600">(optional)</span>
                        </label>
                        <textarea
                            value={steps}
                            onChange={(e) => setSteps(e.target.value)}
                            placeholder="1. Click on...&#10;2. Then...&#10;3. Bug appears when..."
                            className="w-full bg-gray-800 border border-gray-700 rounded-lg px-3 py-2 text-sm text-gray-200 placeholder-gray-500 focus:outline-none focus:ring-1 focus:ring-blue-500 focus:border-blue-500 resize-none"
                            rows={3}
                        />
                    </div>
                </div>

                {/* Footer */}
                <div className="flex items-center justify-between p-4 border-t border-gray-800 bg-gray-900/50">
                    <p className="text-xs text-gray-500">
                        Copy the report and share with support
                    </p>
                    <div className="flex gap-2">
                        <button
                            onClick={onClose}
                            className="px-4 py-2 text-sm text-gray-400 hover:text-gray-300 transition-colors"
                        >
                            Cancel
                        </button>
                        <button
                            onClick={handleCopy}
                            disabled={!description.trim()}
                            className={clsx(
                                'flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium transition-all',
                                description.trim()
                                    ? 'bg-blue-600 hover:bg-blue-500 text-white'
                                    : 'bg-gray-800 text-gray-600 cursor-not-allowed'
                            )}
                        >
                            {copied ? (
                                <>
                                    <Check className="w-4 h-4" />
                                    Copied!
                                </>
                            ) : (
                                <>
                                    <Copy className="w-4 h-4" />
                                    Copy Report
                                </>
                            )}
                        </button>
                    </div>
                </div>
            </div>
        </div>
    )
}
